name: Deploy Python
on:
  workflow_call:
    inputs:
      env: 
        required: true
        type: string
      deploy:
        required: true
        type: boolean
        default: false
    secrets:
      AZURE_CREDENTIALS: 
        required: true
      AZURE_FUNCTIONAPP_PUBLISH_PROFILE:
        required: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{inputs.env}}
      deployment: ${{inputs.deploy}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: get_pushed_tag
        id: get_latest_tag
        run: |
          git fetch --tags --force
          latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
          if [[ -z $latest_tag ]]; then
            latest_tag='v0.0.0'
          fi
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"
      
      - name: deploy
        run: |
          echo "Deploying to version: ${{steps.get_latest_tag.outputs.tag}}"

      - name: artifact zip
        run: zip deployment.zip function_app.py main.py database.py host.json requirements.txt

      - name: Upload zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment.zip
          path: deployment.zip
          retention-days: 1
      
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Run the Azure Functions action'
        uses: Azure/functions-action@v1
        id: deploy-to-function-app
        with:
          app-name: func-todo-backend
          package: deployment.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}


      