name: Deploy Node
on:
  workflow_call:
    inputs:
      env: 
        required: true
        type: string
      node-version:
        type: string
        default: '24'
    secrets:
      AZURE_REGISTRY_USERNAME:
        required: true
      AZURE_REGISTRY_PASSWORD:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
env:
  AZURE_CONTAINER_REGISTRY: crtodo${{inputs.env}}     
  CONTAINER_APP_NAME: ca-frontend-todo-${{inputs.env}}
  RESOURCE_GROUP: rg-containers-todo-${{inputs.env}}
  CONTAINER_APP_ENVIRONMENT: cae-todo-${{inputs.env}}
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: ${{inputs.env}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: get_pushed_tag
        id: get_latest_tag
        run: |
          git fetch --tags --force
          latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
          if [[ -z $latest_tag ]]; then
            latest_tag='v0.0.0'
          fi
          echo "tag=$latest_tag" >> "$GITHUB_OUTPUT"
      
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME}}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ steps.get_latest_tag.outputs.tag }}
          provenance: false

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure Container App Deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/frontend:${{ steps.get_latest_tag.outputs.tag }}
          acrUsername: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          acrPassword: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT }}