on: 
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
    inputs:
      env:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -input=false | tee plan.txt 
      
      - name: Print job summary
        uses: sgametrio/terraform-summary-action@v1.1
        with:
          log-file: plan.txt
          title: Plan Summary

  apply:
    needs: plan
    name: Terraform init + apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve