on: 
  workflow_call

jobs:
  plan:
    name: Terraform init + plan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v4

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan